//! Explicit diagnostic evidence classification table.

use std::sync::LazyLock;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum DiagnosticClass {
    Analysis { evidence: lute_core_span::Evidence },
    SourceError,
}

pub const BOUNDED_CLOCK_SCOPE: &str = "declared clock windows; no path search";

#[derive(Clone, Copy, Debug)]
pub struct DiagnosticClassifications;

impl std::ops::Deref for DiagnosticClassifications {
    type Target = [(&'static str, DiagnosticClass)];
    fn deref(&self) -> &Self::Target {
        &TABLE
    }
}

impl IntoIterator for DiagnosticClassifications {
    type Item = &'static (&'static str, DiagnosticClass);
    type IntoIter = std::slice::Iter<'static, (&'static str, DiagnosticClass)>;
    fn into_iter(self) -> Self::IntoIter {
        TABLE.iter()
    }
}

impl<'a> IntoIterator for &'a DiagnosticClassifications {
    type Item = &'a (&'static str, DiagnosticClass);
    type IntoIter = std::slice::Iter<'a, (&'static str, DiagnosticClass)>;
    fn into_iter(self) -> Self::IntoIter {
        TABLE.iter()
    }
}

pub static DIAGNOSTIC_CLASSIFICATIONS: DiagnosticClassifications = DiagnosticClassifications;

static TABLE: LazyLock<Vec<(&'static str, DiagnosticClass)>> = LazyLock::new(|| vec![
    ("E-ACCEPT-TARGET", DiagnosticClass::SourceError),
    ("E-ADVANCE-CASCADE", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-AGE-GATE", DiagnosticClass::SourceError),
    ("E-APP-READONLY", DiagnosticClass::SourceError),
    ("E-ARM-DEAD", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-AS-REMOVED", DiagnosticClass::SourceError),
    ("E-ASSET-DECOMPOSE", DiagnosticClass::SourceError),
    ("E-ASSET-SEGMENT", DiagnosticClass::SourceError),
    ("E-ASSET-UNKNOWN-ID", DiagnosticClass::SourceError),
    ("E-AT-CONTEXT", DiagnosticClass::SourceError),
    ("E-ATTR-DEF-DYNAMIC", DiagnosticClass::SourceError),
    ("E-ATTR-QUOTE", DiagnosticClass::SourceError),
    ("E-ATTR-TYPE", DiagnosticClass::SourceError),
    ("E-AUTHOR-CASE", DiagnosticClass::SourceError),
    ("E-BAD-ENUM", DiagnosticClass::SourceError),
    ("E-BEAT-ATTR", DiagnosticClass::SourceError),
    ("E-BEAT-ID-DUP", DiagnosticClass::SourceError),
    ("E-BEAT-UNREACHABLE", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-BRANCH-ALL-GUARDED", DiagnosticClass::SourceError),
    ("E-BRANCH-EMPTY", DiagnosticClass::SourceError),
    ("E-BRANCH-PROMPT", DiagnosticClass::SourceError),
    ("E-BRANCH-TIMEOUT", DiagnosticClass::SourceError),
    ("E-CAMERA-EMPTY", DiagnosticClass::SourceError),
    ("E-CAMERA-REMOVED", DiagnosticClass::SourceError),
    ("E-CAPABILITY-MISMATCH", DiagnosticClass::SourceError),
    ("E-CAST-UNKNOWN", DiagnosticClass::SourceError),
    ("E-CEL-PARSE", DiagnosticClass::SourceError),
    ("E-CEL-PROFILE", DiagnosticClass::SourceError),
    ("E-CEL-TYPE", DiagnosticClass::SourceError),
    ("E-CG-LAYOUT", DiagnosticClass::SourceError),
    ("E-CHAPTERS", DiagnosticClass::SourceError),
    ("E-CHECK-ENGINE-SEMANTICS", DiagnosticClass::SourceError),
    ("E-CHOICE-DUP", DiagnosticClass::SourceError),
    ("E-CHOICELOG-READ", DiagnosticClass::SourceError),
    ("E-CLIP-OVERLAP", DiagnosticClass::SourceError),
    ("E-CLIP-TIMING", DiagnosticClass::SourceError),
    ("E-CLOCK-DECL", DiagnosticClass::SourceError),
    ("E-CLOCK-END", DiagnosticClass::SourceError),
    ("E-COMMENT-UNTERMINATED", DiagnosticClass::SourceError),
    ("E-COMPILE-COMPONENT", DiagnosticClass::SourceError),
    ("E-COMPILE-EXPAND", DiagnosticClass::SourceError),
    ("E-COMPILE-INTERNAL", DiagnosticClass::SourceError),
    ("E-COMPONENT-ARG", DiagnosticClass::SourceError),
    ("E-COMPONENT-BODY", DiagnosticClass::SourceError),
    ("E-COMPONENT-CYCLE", DiagnosticClass::SourceError),
    ("E-COMPONENT-DUP", DiagnosticClass::SourceError),
    ("E-COMPONENT-INSTANCE-DUPLICATE", DiagnosticClass::SourceError),
    ("E-COMPONENT-INSTANCE-INVALID", DiagnosticClass::SourceError),
    ("E-COMPONENT-PARSE", DiagnosticClass::SourceError),
    ("E-COMPONENT-STATE", DiagnosticClass::SourceError),
    ("E-COMPONENT-UNDECLARED", DiagnosticClass::SourceError),
    ("E-CONN-CYCLE", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-CONN-EPISODE-ID-DUP", DiagnosticClass::SourceError),
    ("E-CONN-FORMULA-TOO-COMPLEX", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-CONN-PROFILE", DiagnosticClass::SourceError),
    ("E-CONN-UNKNOWN-NODE", DiagnosticClass::SourceError),
    ("E-CONN-UNREACHABLE", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-CONSTRAINT-DECL", DiagnosticClass::SourceError),
    ("E-CONSTRAINT-VIOLATED", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Bounded { scope: BOUNDED_CLOCK_SCOPE.to_string() } }),
    ("E-CONTENT-LINE-BRACKET", DiagnosticClass::SourceError),
    ("E-CONTENT-OUTSIDE-SECTION", DiagnosticClass::SourceError),
    ("E-CONTEXT-POSITION", DiagnosticClass::SourceError),
    ("E-CONTEXT-TARGET", DiagnosticClass::SourceError),
    ("E-DATALOG-FUNCTION", DiagnosticClass::SourceError),
    ("E-DATALOG-GUARD-FACT", DiagnosticClass::SourceError),
    ("E-DATALOG-PARSE", DiagnosticClass::SourceError),
    ("E-DATALOG-UNSAFE", DiagnosticClass::SourceError),
    ("E-DATALOG-UNSTRATIFIED", DiagnosticClass::SourceError),
    ("E-DEF-DECL", DiagnosticClass::SourceError),
    ("E-DEFAULTS-KEY", DiagnosticClass::SourceError),
    ("E-DELIVERY-CONFLICT", DiagnosticClass::SourceError),
    ("E-DELIVERY-FLAG-VALUE", DiagnosticClass::SourceError),
    ("E-DELIVERY-NARRATOR", DiagnosticClass::SourceError),
    ("E-DEPENDS-CYCLE", DiagnosticClass::SourceError),
    ("E-DEPENDS-UNRESOLVED", DiagnosticClass::SourceError),
    ("E-DEPENDS-VERSION", DiagnosticClass::SourceError),
    ("E-DERIVE-TIER", DiagnosticClass::SourceError),
    ("E-DERIVE-UNDECLARED", DiagnosticClass::SourceError),
    ("E-DERIVED-WRITE", DiagnosticClass::SourceError),
    ("E-DIFF-INPUT", DiagnosticClass::SourceError),
    ("E-DIFF-MODEL", DiagnosticClass::SourceError),
    ("E-DOLLAR-OUTSIDE-MATCH", DiagnosticClass::SourceError),
    ("E-DOMAIN-DUP", DiagnosticClass::SourceError),
    ("E-DOMAIN-NAME-CLASH", DiagnosticClass::SourceError),
    ("E-DOMAIN-UNKNOWN", DiagnosticClass::SourceError),
    ("E-DUP-BRANCH", DiagnosticClass::SourceError),
    ("E-DUP-LINE-CODE", DiagnosticClass::SourceError),
    ("E-DUP-TRACK", DiagnosticClass::SourceError),
    ("E-DUP-VOICEKEY", DiagnosticClass::SourceError),
    ("E-ENGINE-IR-VERSION", DiagnosticClass::SourceError),
    ("E-ENGINE-MATRIX", DiagnosticClass::SourceError),
    ("E-ENGINE-OWNED-WRITE", DiagnosticClass::SourceError),
    ("E-ENGINE-SEMANTICS", DiagnosticClass::SourceError),
    ("E-ENTITY-KIND-CLASH", DiagnosticClass::SourceError),
    ("E-ENTITY-KIND-SHAPE", DiagnosticClass::SourceError),
    ("E-ENTRY-ATTR", DiagnosticClass::SourceError),
    ("E-ENTRY-ID-DUP", DiagnosticClass::SourceError),
    ("E-ENTRY-SERIES-ORDER", DiagnosticClass::SourceError),
    ("E-ENTRY-UNREACHABLE", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-ENUM-DEFAULT-NOT-MEMBER", DiagnosticClass::SourceError),
    ("E-ENUM-EXITS-NOT-MEMBER", DiagnosticClass::SourceError),
    ("E-ENUM-LABEL-NOT-MEMBER", DiagnosticClass::SourceError),
    ("E-ENUM-MISSING-SEMANTICS", DiagnosticClass::SourceError),
    ("E-ENUM-UNEXPECTED-SEMANTICS", DiagnosticClass::SourceError),
    ("E-EXTENDS-RELATION-SIG", DiagnosticClass::SourceError),
    ("E-EXTENDS-STATE-TYPE", DiagnosticClass::SourceError),
    ("E-FACT-DOMAIN", DiagnosticClass::SourceError),
    ("E-FACT-EXCLUSIVE", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-FACT-QUERY", DiagnosticClass::SourceError),
    ("E-FACT-TIER-WRITE", DiagnosticClass::SourceError),
    ("E-FLAG-VALUE", DiagnosticClass::SourceError),
    ("E-FMT", DiagnosticClass::SourceError),
    ("E-FMT-CHECK", DiagnosticClass::SourceError),
    ("E-FRONTMATTER-SCHEMA", DiagnosticClass::SourceError),
    ("E-GRAMMAR-NOT-ADMITTED", DiagnosticClass::SourceError),
    ("E-HUB-NO-EXIT", DiagnosticClass::SourceError),
    ("E-IDENTITY-TEMPLATE", DiagnosticClass::SourceError),
    ("E-INERT-TITLE", DiagnosticClass::SourceError),
    ("E-INTERP-DEF", DiagnosticClass::SourceError),
    ("E-INTERP-UNTERMINATED", DiagnosticClass::SourceError),
    ("E-INTO-TARGET", DiagnosticClass::SourceError),
    ("E-INTO-UNDECLARED", DiagnosticClass::SourceError),
    ("E-INTO-VALUE", DiagnosticClass::SourceError),
    ("E-IR-REMOVED-FIELD", DiagnosticClass::SourceError),
    ("E-JUMP-BACKWARD", DiagnosticClass::SourceError),
    ("E-JUMP-UNDEFINED", DiagnosticClass::SourceError),
    ("E-KIND-MISSING", DiagnosticClass::SourceError),
    ("E-KIND-NAME-CLASH", DiagnosticClass::SourceError),
    ("E-L10N-MODIFIERS", DiagnosticClass::SourceError),
    ("E-LABEL-DUP", DiagnosticClass::SourceError),
    ("E-LEGACY-CONTENT-SIGIL", DiagnosticClass::SourceError),
    ("E-LINT-CONFIG", DiagnosticClass::SourceError),
    ("E-LINT-EXPR", DiagnosticClass::SourceError),
    ("E-LINT-RULE", DiagnosticClass::SourceError),
    ("E-LOCALE-BUNDLE", DiagnosticClass::SourceError),
    ("E-LOGIC-CONTENT", DiagnosticClass::SourceError),
    ("E-LOWER-RECORD-FIELD", DiagnosticClass::SourceError),
    ("E-LOWER-RECORD-UNKNOWN", DiagnosticClass::SourceError),
    ("E-MANIFEST", DiagnosticClass::SourceError),
    ("E-MANIFEST-KEY", DiagnosticClass::SourceError),
    ("E-MATCH-DUP-OTHERWISE", DiagnosticClass::SourceError),
    ("E-MATCH-NO-SUBJECT", DiagnosticClass::SourceError),
    ("E-MATCH-RELATION-SUBJECT", DiagnosticClass::SourceError),
    ("E-MAYBE-UNSET", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-META-ID", DiagnosticClass::SourceError),
    ("E-META-MISSING", DiagnosticClass::SourceError),
    ("E-META-PARSE", DiagnosticClass::SourceError),
    ("E-META-UNKNOWN-KEY", DiagnosticClass::SourceError),
    ("E-META-VALUE", DiagnosticClass::SourceError),
    ("E-MISSING-ATTR", DiagnosticClass::SourceError),
    ("E-MOCK-SUBJECT", DiagnosticClass::SourceError),
    ("E-MONO-NO-POV", DiagnosticClass::SourceError),
    ("E-MONO-POV", DiagnosticClass::SourceError),
    ("E-NONEXHAUSTIVE", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-OBJECTIVE-CONTRADICTION", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-OBJECTIVE-ID-DUP", DiagnosticClass::SourceError),
    ("E-OBJECTIVE-ID-MISSING", DiagnosticClass::SourceError),
    ("E-OBJECTIVE-MISSING-DONE", DiagnosticClass::SourceError),
    ("E-OBJECTIVE-QUEST-DONE", DiagnosticClass::SourceError),
    ("E-OBJECTIVE-UNSATISFIABLE", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-OCCASION-GATE", DiagnosticClass::SourceError),
    ("E-OCCASION-UNKNOWN", DiagnosticClass::SourceError),
    ("E-ON-NO-EVENT", DiagnosticClass::SourceError),
    ("E-PATCH-CHECK", DiagnosticClass::SourceError),
    ("E-PATCH-EDIT", DiagnosticClass::SourceError),
    ("E-PATCH-PRESERVE", DiagnosticClass::SourceError),
    ("E-PATCH-STALE", DiagnosticClass::SourceError),
    ("E-PATCH-TARGET", DiagnosticClass::SourceError),
    ("E-PATH-IDENT", DiagnosticClass::SourceError),
    ("E-PERMISSION-BRIDGE", DiagnosticClass::SourceError),
    ("E-PERMISSION-DIRECTIVE", DiagnosticClass::SourceError),
    ("E-PERMISSION-FACT", DiagnosticClass::SourceError),
    ("E-PERMISSION-PROFILE", DiagnosticClass::SourceError),
    ("E-PERMISSION-QUEST", DiagnosticClass::SourceError),
    ("E-PERMISSION-REWARD", DiagnosticClass::SourceError),
    ("E-PERMISSION-STATE", DiagnosticClass::SourceError),
    ("E-PERSIST-REMOVED", DiagnosticClass::SourceError),
    ("E-PLUGIN-ASSET-SEGMENT-TYPE", DiagnosticClass::SourceError),
    ("E-PLUGIN-DUP-ACROSS", DiagnosticClass::SourceError),
    ("E-PLUGIN-DUP-ID", DiagnosticClass::SourceError),
    ("E-PLUGIN-INVALID-DIRECTIVE", DiagnosticClass::SourceError),
    ("E-PLUGIN-IO", DiagnosticClass::SourceError),
    ("E-PLUGIN-KEY", DiagnosticClass::SourceError),
    ("E-PLUGIN-MANIFEST", DiagnosticClass::SourceError),
    ("E-PLUGIN-MISSING-ACTIVE", DiagnosticClass::SourceError),
    ("E-PLUGIN-MISSING-EXPORT", DiagnosticClass::SourceError),
    ("E-PLUGIN-OPTION-TYPE", DiagnosticClass::SourceError),
    ("E-PLUGIN-OPTION-UNKNOWN", DiagnosticClass::SourceError),
    ("E-PLUGIN-PARSE", DiagnosticClass::SourceError),
    ("E-PLUGIN-RESERVED-NAME", DiagnosticClass::SourceError),
    ("E-PLUGIN-RESERVED-STAMP-ATTR", DiagnosticClass::SourceError),
    ("E-PLUGIN-UNKNOWN-ASSETKIND", DiagnosticClass::SourceError),
    ("E-PLUGIN-UNKNOWN-EXPORT", DiagnosticClass::SourceError),
    ("E-PLUGIN-UNKNOWN-REWARD-TARGET", DiagnosticClass::SourceError),
    ("E-PLURAL-FORM", DiagnosticClass::SourceError),
    ("E-PROFILE-EXTENDS-CYCLE", DiagnosticClass::SourceError),
    ("E-PROFILE-UNKNOWN", DiagnosticClass::SourceError),
    ("E-PROJECT-CONFIG", DiagnosticClass::SourceError),
    ("E-QUEST-ID-DUP", DiagnosticClass::SourceError),
    ("E-QUEST-ID-MISSING", DiagnosticClass::SourceError),
    ("E-QUEST-MULTI-PARENT", DiagnosticClass::SourceError),
    ("E-QUEST-REF-UNKNOWN", DiagnosticClass::SourceError),
    ("E-QUEST-RESERVED-DECL", DiagnosticClass::SourceError),
    ("E-QUEST-RESERVED-WRITE", DiagnosticClass::SourceError),
    ("E-QUEST-TIER-MIX", DiagnosticClass::SourceError),
    ("E-QUEST-TREE-CYCLE", DiagnosticClass::SourceError),
    ("E-QUEST-UNREACHABLE", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-REF-ARG-TYPE", DiagnosticClass::SourceError),
    ("E-REF-ARITY", DiagnosticClass::SourceError),
    ("E-REF-TYPE", DiagnosticClass::SourceError),
    ("E-RELATION-ARITY", DiagnosticClass::SourceError),
    ("E-RELATION-DECL", DiagnosticClass::SourceError),
    ("E-RELATION-DOMAIN", DiagnosticClass::SourceError),
    ("E-RELATION-DUP", DiagnosticClass::SourceError),
    ("E-RELATION-EMPTY", DiagnosticClass::SourceError),
    ("E-RELATION-RESERVED-WRITE", DiagnosticClass::SourceError),
    ("E-RELATION-UNKNOWN", DiagnosticClass::SourceError),
    ("E-REMOVED-ATTR", DiagnosticClass::SourceError),
    ("E-REMOVED-PROJECT-KEY", DiagnosticClass::SourceError),
    ("E-REMOVED-TAG", DiagnosticClass::SourceError),
    ("E-RENAME-LEDGER", DiagnosticClass::SourceError),
    ("E-RENAME-LEDGER-CYCLE", DiagnosticClass::SourceError),
    ("E-RENAME-LEDGER-STALE", DiagnosticClass::SourceError),
    ("E-RENAMED-ATTR", DiagnosticClass::SourceError),
    ("E-RENAMED-DIRECTIVE", DiagnosticClass::SourceError),
    ("E-RENAMED-TAG-ATTR", DiagnosticClass::SourceError),
    ("E-RESERVED-NAME", DiagnosticClass::SourceError),
    ("E-RETRACT-WILDCARD-ASSERT", DiagnosticClass::SourceError),
    ("E-REWARD-ATTR", DiagnosticClass::SourceError),
    ("E-REWARD-DUP", DiagnosticClass::SourceError),
    ("E-REWARD-KIND", DiagnosticClass::SourceError),
    ("E-REWARD-TARGET", DiagnosticClass::SourceError),
    ("E-RULE-AGGREGATE-CYCLE", DiagnosticClass::SourceError),
    ("E-RULE-EXCLUSIVE", DiagnosticClass::SourceError),
    ("E-RULE-GUARD-DEF", DiagnosticClass::SourceError),
    ("E-RUN-OWNED-WRITE", DiagnosticClass::SourceError),
    ("E-SEASON-DECL", DiagnosticClass::SourceError),
    ("E-SECTION-DUP", DiagnosticClass::SourceError),
    ("E-SECTION-SUFFIX", DiagnosticClass::SourceError),
    ("E-SEMANTICS-UNKNOWN", DiagnosticClass::SourceError),
    ("E-SET-OP-TYPE", DiagnosticClass::SourceError),
    ("E-SET-SHAPE", DiagnosticClass::SourceError),
    ("E-SET-TYPE", DiagnosticClass::SourceError),
    ("E-STATE-COLLECTION", DiagnosticClass::SourceError),
    ("E-STATE-DECL", DiagnosticClass::SourceError),
    ("E-STATE-DECL-CONFLICT", DiagnosticClass::SourceError),
    ("E-STATE-MAYBE-UNAVAILABLE", DiagnosticClass::SourceError),
    ("E-STATE-NAMESPACE", DiagnosticClass::SourceError),
    ("E-STATE-REDECLARE", DiagnosticClass::SourceError),
    ("E-STATE-SHAPE-CYCLE", DiagnosticClass::SourceError),
    ("E-STREAM-BODY", DiagnosticClass::SourceError),
    ("E-STREAM-CLOSED", DiagnosticClass::SourceError),
    ("E-STREAM-PREFIX-CHANGED", DiagnosticClass::SourceError),
    ("E-STREAM-TEMPLATE", DiagnosticClass::SourceError),
    ("E-STRING-ESCAPE", DiagnosticClass::SourceError),
    ("E-SUBQUEST-REARM", DiagnosticClass::SourceError),
    ("E-TAG-INLINE-BODY", DiagnosticClass::SourceError),
    ("E-TAG-NOT-ONE-LINE", DiagnosticClass::SourceError),
    ("E-TASK-TRAP", DiagnosticClass::SourceError),
    ("E-TEMPLATE", DiagnosticClass::SourceError),
    ("E-TEMPORAL-ARG", DiagnosticClass::SourceError),
    ("E-TEST-FILE", DiagnosticClass::SourceError),
    ("E-TEST-KEY", DiagnosticClass::SourceError),
    ("E-TEST-LORE", DiagnosticClass::SourceError),
    ("E-TEST-NEEDLE", DiagnosticClass::SourceError),
    ("E-TEST-NO-EXPECT", DiagnosticClass::SourceError),
    ("E-TEXT-ESCAPE", DiagnosticClass::SourceError),
    ("E-TEXT-MODIFIER", DiagnosticClass::SourceError),
    ("E-TIME-RESOLUTION", DiagnosticClass::SourceError),
    ("E-TIMELINE-CONTENT", DiagnosticClass::SourceError),
    ("E-TIMELINE-DURATION", DiagnosticClass::SourceError),
    ("E-TRACE-ACCEPT", DiagnosticClass::SourceError),
    ("E-TRACE-BEAT", DiagnosticClass::SourceError),
    ("E-TRACE-CHOICE", DiagnosticClass::SourceError),
    ("E-TRACE-ENTRY", DiagnosticClass::SourceError),
    ("E-TRACE-EVENT", DiagnosticClass::SourceError),
    ("E-TRACE-MOCK-FACT", DiagnosticClass::SourceError),
    ("E-TRACE-MOCK-PARSE", DiagnosticClass::SourceError),
    ("E-TRACE-MOCK-TYPE", DiagnosticClass::SourceError),
    ("E-TRACE-MOCK-UNDECLARED", DiagnosticClass::SourceError),
    ("E-TRACK-KEY", DiagnosticClass::SourceError),
    ("E-UNCLASSIFIED", DiagnosticClass::SourceError),
    ("E-UNCLOSED-TAG", DiagnosticClass::SourceError),
    ("E-UNDECLARED", DiagnosticClass::SourceError),
    ("E-UNDECLARED-REF", DiagnosticClass::SourceError),
    ("E-UNKNOWN-ATTR", DiagnosticClass::SourceError),
    ("E-UNKNOWN-DIRECTIVE", DiagnosticClass::SourceError),
    ("E-UNKNOWN-EVENT", DiagnosticClass::SourceError),
    ("E-UNKNOWN-ID", DiagnosticClass::SourceError),
    ("E-UNKNOWN-KIND", DiagnosticClass::SourceError),
    ("E-UNSET-LITERAL", DiagnosticClass::SourceError),
    ("E-UNSET-UNCOVERED", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-USES-CYCLE", DiagnosticClass::SourceError),
    ("E-USES-DUP-DEF", DiagnosticClass::SourceError),
    ("E-USES-DUP-RELATION", DiagnosticClass::SourceError),
    ("E-USES-DUP-STATE", DiagnosticClass::SourceError),
    ("E-USES-NOT-FOUND", DiagnosticClass::SourceError),
    ("E-USES-PARSE", DiagnosticClass::SourceError),
    ("E-VALIDAT-DERIVED", DiagnosticClass::SourceError),
    ("E-WHEN-LITERAL-DOMAIN", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("E-WHEN-PATTERN", DiagnosticClass::SourceError),
    ("E-WHEN-RANGE", DiagnosticClass::SourceError),
    ("E-WHEN-UNSET-SUBJECT", DiagnosticClass::SourceError),
    ("E-WRITE-CONFLICT", DiagnosticClass::SourceError),
    ("W-ASSET-PLACEHOLDER", DiagnosticClass::SourceError),
    ("W-BEAT-ONCE-RUN-USER", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Heuristic }),
    ("W-BEAT-PRIORITY-TIE", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Heuristic }),
    ("W-BEAT-SHADOWED", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("W-BEAT-SPENT-AT-START", DiagnosticClass::SourceError),
    ("W-BEAT-UNRAISED", DiagnosticClass::SourceError),
    ("W-BRANCH-ID-SHARED", DiagnosticClass::SourceError),
    ("W-CAST-ABSENT", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("W-CATALOG-STALE", DiagnosticClass::SourceError),
    ("W-CHAPTER-ORDER", DiagnosticClass::SourceError),
    ("W-CHAPTER-STALL", DiagnosticClass::SourceError),
    ("W-CODE-AFTER-END", DiagnosticClass::SourceError),
    ("W-CODE-AFTER-JUMP", DiagnosticClass::SourceError),
    ("W-COMPONENT-INSTANCE-UNTAGGED", DiagnosticClass::SourceError),
    ("W-COMPONENT-UNVERIFIED", DiagnosticClass::SourceError),
    ("W-DEADLINE-BEFORE-DONE", DiagnosticClass::SourceError),
    ("W-DEADLINE-BEFORE-WINDOW", DiagnosticClass::SourceError),
    ("W-DEADLINE-NEVER", DiagnosticClass::SourceError),
    ("W-DEF-UNUSED", DiagnosticClass::SourceError),
    ("W-DERIVE-NO-RULES", DiagnosticClass::SourceError),
    ("W-DISPLAY-NAME-DUP", DiagnosticClass::SourceError),
    ("W-DOMAIN-UNREAD", DiagnosticClass::SourceError),
    ("W-ENTRY-REF-UNKNOWN", DiagnosticClass::SourceError),
    ("W-ENTRY-WRITE-REREAD", DiagnosticClass::SourceError),
    ("W-EXIT-INERT", DiagnosticClass::SourceError),
    ("W-FACT-GUARANTEED", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("W-INTO-SET-DUP", DiagnosticClass::SourceError),
    ("W-L10N-MISSING", DiagnosticClass::SourceError),
    ("W-LINE-CODE-UNTAGGED", DiagnosticClass::SourceError),
    ("W-LUTE-VERSION-STALE", DiagnosticClass::SourceError),
    ("W-META-LEGACY", DiagnosticClass::SourceError),
    ("W-OBJECTIVE-HIDDEN", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("W-OBJECTIVE-STRANDED", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Bounded { scope: BOUNDED_CLOCK_SCOPE.to_string() } }),
    ("W-OTHERWISE-DEAD", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Proven }),
    ("W-OVERLAP-ARMS", DiagnosticClass::SourceError),
    ("W-PROJECT-INERT", DiagnosticClass::SourceError),
    ("W-QUEST-HANDLER-DEAD", DiagnosticClass::SourceError),
    ("W-QUEST-NEVER-ACCEPTED", DiagnosticClass::SourceError),
    ("W-QUEST-REARM-CONSTANT", DiagnosticClass::SourceError),
    ("W-QUEST-REF-UNKNOWN", DiagnosticClass::SourceError),
    ("W-QUEST-STATE-HAS", DiagnosticClass::SourceError),
    ("W-QUEST-TIER-IMPLICIT", DiagnosticClass::SourceError),
    ("W-RELATION-TIER-IMPLICIT", DiagnosticClass::SourceError),
    ("W-RELATION-UNREAD", DiagnosticClass::SourceError),
    ("W-REWARD-DOUBLE-CREDIT", DiagnosticClass::SourceError),
    ("W-SEASON-UNGATED", DiagnosticClass::SourceError),
    ("W-SLOT-CONTENTION", DiagnosticClass::Analysis { evidence: lute_core_span::Evidence::Bounded { scope: BOUNDED_CLOCK_SCOPE.to_string() } }),
    ("W-SPENT-BY-REVERSIBLE", DiagnosticClass::SourceError),
    ("W-STAGE-ABSENT", DiagnosticClass::SourceError),
    ("W-TEMPLATE-DOT-PARAM", DiagnosticClass::SourceError),
    ("W-TEMPLATE-OVERRIDE", DiagnosticClass::SourceError),
    ("W-TERMINAL-PERSISTENT", DiagnosticClass::SourceError),
    ("W-TEXT-BRACKET-LABEL", DiagnosticClass::SourceError),
    ("W-TEXT-COMMENT-LIKE", DiagnosticClass::SourceError),
    ("W-TEXT-GLUE", DiagnosticClass::SourceError),
    ("W-TEXT-LOOKS-LIKE-REF", DiagnosticClass::SourceError),
    ("W-TEXT-SINGLE-BRACE", DiagnosticClass::SourceError),
    ("W-TIMELINE-CLIPS", DiagnosticClass::SourceError),
    ("W-TIMELINE-TOTAL", DiagnosticClass::SourceError),
    ("W-TIMELINE-TRACKS", DiagnosticClass::SourceError),
    ("W-TRACE-MOCK-UNPRODUCIBLE", DiagnosticClass::SourceError),
    ("W-WHEN-TEST-LITERAL", DiagnosticClass::SourceError),
    ("W-WIP", DiagnosticClass::SourceError),
]);

pub fn classification(code: &str) -> Option<DiagnosticClass> {
    DIAGNOSTIC_CLASSIFICATIONS.iter().find(|(candidate, _)| *candidate == code).map(|(_, class)| class.clone())
}

/// Apply the registry classification at the checker boundary.
pub fn annotate(diagnostics: &mut [lute_core_span::Diagnostic]) {
    for diagnostic in diagnostics {
        if diagnostic.evidence.is_some() {
            continue;
        }
        if let Some(DiagnosticClass::Analysis { evidence }) =
            classification(diagnostic.code.as_str())
        {
            diagnostic.evidence = Some(evidence);
        }
    }
}
