[package]
name = "lute-resolve"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
lute-core-span = { path = "../lute-core-span" }
lute-cel = { path = "../lute-cel" }
lute-check = { path = "../lute-check" }
lute-manifest = { path = "../lute-manifest" }
lute-semantic = { path = "../lute-semantic" }
lute-syntax = { path = "../lute-syntax" }
serde = { workspace = true }
serde_yaml = { workspace = true }
