[package]
name = "lute-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "lute-bench"

[dependencies]
lute-check = { path = "../lute-check" }
lute-model = { path = "../lute-model" }
lute-semantic = { path = "../lute-semantic" }
lute-trace = { path = "../lute-trace" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
